### ISSUE TITLE
setting an institution in profile doesn't work

### ISSUE THREAD

**Issue by colinsauze** [fws-hub/xPapers#14]
When you enter an institution in the profile page it just disappears. It seems you have to click on "institute not listed" but even this is not reliable. 

Is there an institute list being built somewhere? If so where? Can we populate it from papers?

**Comment by timinwales** [comment]
I seem to have managed to put Aberystwyth University in the "Institutions" dialogue box and it appears in my profile.

**Comment by colinsauze** [comment]
I've now populated some entries into the insts table and this has solved the problem.
